defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

data:
  csv_file: "./data/data_2016.csv"

model:
  name: "dscovry"
  version: 1.0

optim:
  beta1: 0.9
  beta2: 0.95
  weight_decay: 1e-1

hyper:
  pretrained: True
  n_layers: 2
  n_hidden: 128
  batch_size: 32
  dropout: 0.2
  lr: 1e-3
  epochs: 20
  eval_iters: 1
  use_amp: True

# hydra customizations
hydra:  
  output_subdir: null  
  run:  
    dir: .
  job_logging:
    disable_existing_loggers: true
    version: 1
    formatters:
      colorlog:
        '()': 'colorlog.ColoredFormatter'
        format: "[%(cyan)s%(asctime)s%(reset)s][%(green)s%(levelname)s%(reset)s] %(message)s"
    handlers:
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers: [console]
